version: '3.8'
services:
  app:
    build: ./app
    command: ["bundle","exec","rackup","--host","0.0.0.0","--port","4567"]
    restart: always
    volumes:
      - ./app/:/app
  proxy:
    image: nwtgck/nginx-http3
    build: ./proxy
    #代わりにimage #build: ./proxy
    restart: always
    #command: ["nginx-debug", "-g", "daemon off;"]
    # ↑ Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "nginx-debug": executable file not found in $PATH: unknown
    volumes:
      - ./proxy/nginx.conf:/usr/local/nginx/conf/nginx.conf
      - ./ssl/server.crt:/etc/ssl/certs/server.crt
      - ./ssl/server.key:/etc/ssl/private/server.key
    ports:
      - 443:443
      - 443:443/udp
      - 80:80
    depends_on:
      - app


