version: '3.8'
services:
  app:
    build: ./app
    command: ["bundle","exec","rackup","--host","0.0.0.0","--port","4567"]
    restart: always
    volumes:
      - ./app/:/app
  web:
    image: nwtgck/nginx-http3
    build: ./web
    restart: always
    volumes:
      - ./web/default.conf:/usr/local/nginx/conf/nginx.conf
      - ./ssl/server.crt:/etc/ssl/certs/server.crt
      - ./ssl/server.key:/etc/ssl/private/server.key
    ports:
      - 443:443
      - 443:443/udp
      - 80:80
    depends_on:
      - app


